# Generated by Django 4.2.4 on 2023-09-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_delete_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
