# Generated by Django 4.2.4 on 2023-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_remove_project_team_id_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estado',
            field=models.CharField(default='En desarrollo', max_length=13),
        ),
    ]
