# Generated by Django 4.2.4 on 2023-09-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_project_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_assigned_to_user_id',
        ),
    ]
